In [5]:
#Importation du fichier
import pandas as pd
df=pd.read_csv("../data/processed/dataset_credit.csv")
df.head()

,id_credit,nb_transactions_30j,nb_transactions_60j,nb_transactions_90j,nb_jours_actifs_90j,volume_entrant_90j,volume_sortant_90j,ratio_flux_entrant_sortant,montant_moyen_90j,montant_median_90j,regularite_transactions,variation_volume_mensuel,nb_credits_precedents,nb_credits_impayes,nb_retards,retard_moyen_jours,taux_remboursement,montant_credit_demande,duree_credit_demande,defaut
0,cred_002026,8,13,22,19,122738.0,136689.0,0.897936,11792.136364,6776.0,0.211111,-0.448439,0,0,0,NaN,NaN,100000,3,0
1,cred_002225,6,10,13,13,39424.0,17171.0,2.295964,4353.461538,4152.0,0.144444,0.126577,0,0,0,NaN,NaN,5000,3,0
2,cred_001582,6,11,21,21,43873.0,77845.0,0.563594,5796.095238,4109.0,0.233333,-0.472710,0,0,0,NaN,NaN,25000,6,1
3,cred_002437,5,14,19,18,49221.0,71995.0,0.683672,6379.789474,6067.0,0.200000,-0.248396,0,0,0,NaN,NaN,15000,3,0
4,cred_001682,10,16,25,21,63284.0,67362.0,0.939461,5225.840000,4348.0,0.233333,0.158132,0,0,0,NaN,NaN,50000,6,0

In [ ]:
#Nombre de lignes et de colonnes du dataset
df.shape

(2712, 20)

In [7]:
#Valeurs manquantes
df.isnull().sum()

id_credit                        0
nb_transactions_30j              0
nb_transactions_60j              0
nb_transactions_90j              0
nb_jours_actifs_90j              0
volume_entrant_90j               0
volume_sortant_90j               0
ratio_flux_entrant_sortant       0
montant_moyen_90j                0
montant_median_90j               0
regularite_transactions          0
variation_volume_mensuel         0
nb_credits_precedents            0
nb_credits_impayes               0
nb_retards                       0
retard_moyen_jours            1796
taux_remboursement            1796
montant_credit_demande           0
duree_credit_demande             0
defaut                           0
dtype: int64

In [11]:
# Liste des catégories uniques
print(df["retard_moyen_jours"].unique())

[  nan   1.    0.   77.   84.    5.   10.   51.  108.   85.   61.   64.
  80.   37.   67.   35.   55.   43.5  27.5  81.   73.   95.    2.5  58.
 113.   45.  101.   34.5  88.   31.   33.   96.   59.5   2.   15.   99.
 116.   69.  102.   63.   29.  114.  106.   56.5  57.    0.5  46.   50.5
  22.   22.5   7.5  39.   34.  100.   65.   18.5  60.   97.   94.   31.5
  72.  104.   98.  117.   50.    3.5  70.   42.   32.   93.   48.   49.
  66.   54.  119.   83.   47.5  20.5  71.   71.5 109.   24.   36.   41.5
  87.   30.5  82.   40.    3.   16.   15.5  43.  103.   92.   89.   40.5
 107.   45.5  41.   44.   35.5  60.5 111.   49.5 112.   17.   86.   33.5
  21.   74.   38.    5.5  16.5  46.5]

In [12]:
# Étape 1 : Créer une colonne indicateur (1 = Nouveau client sans historique, 0 = Ancien client)
df["sans_historique_credit"] = df["retard_moyen_jours"].isna().astype(int)

# Étape 2 : Remplacer les NaN par 0
df["retard_moyen_jours"] = df["retard_moyen_jours"].fillna(0)
df["taux_remboursement"] = df["taux_remboursement"].fillna(0)

# Étape 3 : Vérifier qu'il n'y a plus aucun trou
print(df[["retard_moyen_jours", "taux_remboursement"]].isnull().sum())

retard_moyen_jours    0
taux_remboursement    0
dtype: int64

In [14]:
#Valeurs manquantes
df.isnull().sum()

id_credit                     0
nb_transactions_30j           0
nb_transactions_60j           0
nb_transactions_90j           0
nb_jours_actifs_90j           0
volume_entrant_90j            0
volume_sortant_90j            0
ratio_flux_entrant_sortant    0
montant_moyen_90j             0
montant_median_90j            0
regularite_transactions       0
variation_volume_mensuel      0
nb_credits_precedents         0
nb_credits_impayes            0
nb_retards                    0
retard_moyen_jours            0
taux_remboursement            0
montant_credit_demande        0
duree_credit_demande          0
defaut                        0
sans_historique_credit        0
dtype: int64

In [15]:
# Compter le nombre de lignes doublons
nb_doublons = df.duplicated().sum()
print(f"Nombre de doublons stricts : {nb_doublons}")

Nombre de doublons stricts : 0

In [16]:
#Verification des types de variables 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2712 entries, 0 to 2711
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id_credit                   2712 non-null   str
 1   nb_transactions_30j         2712 non-null   int64
 2   nb_transactions_60j         2712 non-null   int64
 3   nb_transactions_90j         2712 non-null   int64
 4   nb_jours_actifs_90j         2712 non-null   int64
 5   volume_entrant_90j          2712 non-null   float64
 6   volume_sortant_90j          2712 non-null   float64
 7   ratio_flux_entrant_sortant  2712 non-null   float64
 8   montant_moyen_90j           2712 non-null   float64
 9   montant_median_90j          2712 non-null   float64
 10  regularite_transactions     2712 non-null   float64
 11  variation_volume_mensuel    2712 non-null   float64
 12  nb_credits_precedents       2712 non-null   int64
 13  nb_credits_impayes          2712 non-null   int64
 14  nb_retards                  2712 non-null   int64
 15  retard_moyen_jours          2712 non-null   float64
 16  taux_remboursement          2712 non-null   float64
 17  montant_credit_demande      2712 non-null   int64
 18  duree_credit_demande        2712 non-null   int64
 19  defaut                      2712 non-null   int64
 20  sans_historique_credit      2712 non-null   int64
dtypes: float64(9), int64(11), str(1)
memory usage: 445.1 KB

In [17]:
#Verification des valeurs aberrantes
df.describe()

,nb_transactions_30j,nb_transactions_60j,nb_transactions_90j,nb_jours_actifs_90j,volume_entrant_90j,volume_sortant_90j,ratio_flux_entrant_sortant,montant_moyen_90j,montant_median_90j,regularite_transactions,variation_volume_mensuel,nb_credits_precedents,nb_credits_impayes,nb_retards,retard_moyen_jours,taux_remboursement,montant_credit_demande,duree_credit_demande,defaut,sans_historique_credit
count,2712.000000,2712.000000,2712.000000,2712.000000,2.712000e+03,2.712000e+03,2712.000000,2712.000000,2712.000000,2712.000000,2712.000000,2712.000000,2712.000000,2712.000000,2712.000000,2712.000000,2712.000000,2712.000000,2712.000000,2712.000000
mean,6.183997,12.342920,18.568953,16.747419,7.523195e+04,9.720992e+04,1.357434,9281.144369,4318.179388,0.186082,0.002150,0.418142,0.069690,0.155236,4.563606,0.281895,20663.716814,6.227876,0.158555,0.662242
std,2.546881,3.665117,4.433829,3.787805,9.991506e+04,1.085359e+05,2.423776,7639.574145,1228.457358,0.042087,0.468069,0.635779,0.264616,0.388722,17.483230,0.443711,23109.488006,2.835797,0.365328,0.473033
min,0.000000,3.000000,7.000000,6.000000,1.025000e+03,4.536000e+03,0.012265,2181.636364,1495.000000,0.066667,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5000.000000,3.000000,0.000000,0.000000
25%,4.000000,10.000000,15.000000,14.000000,3.204900e+04,4.580175e+04,0.371738,5400.076667,3457.500000,0.155556,-0.342006,0.000000,0.000000,0.000000,0.000000,0.000000,5000.000000,3.000000,0.000000,0.000000
50%,6.000000,12.000000,18.000000,17.000000,4.913550e+04,6.781350e+04,0.709018,6846.759259,4137.250000,0.188889,-0.000666,0.000000,0.000000,0.000000,0.000000,0.000000,10000.000000,6.000000,0.000000,1.000000
75%,8.000000,15.000000,21.000000,19.000000,7.603150e+04,1.040538e+05,1.389250,9858.972744,4972.750000,0.211111,0.361297,1.000000,0.000000,0.000000,0.000000,1.000000,25000.000000,9.000000,0.000000,1.000000
max,19.000000,25.000000,36.000000,31.000000,1.628654e+06,2.356831e+06,40.620238,103867.000000,12422.000000,0.344444,1.000000,2.000000,2.000000,2.000000,119.000000,1.000000,100000.000000,12.000000,1.000000,1.000000